CREATE TABLE customers (
	id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	email VARCHAR(256) NOT NULL,
    UNIQUE (email)
);

CREATE INDEX

CREATE TABLE time_machines (
	id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	capacity INT NOT NULL,
	status VARCHAR(64) NOT NULL
);

CREATE TABLE time_periods (
	id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	description VARCHAR(256) NOT NULL
);

CREATE TABLE guides (
	id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	speciality VARCHAR(128) NOT NULL
);

CREATE TABLE bookings (
	id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
	costumer_id INT NOT NULL,
	time_machine_id INT NOT NULL,
	time_period_id INT NOT NULL,
	guide_id INT NOT NULL
);